name: deploy to AWS

# main 브랜치에서 푸쉬가 일어났을 때 작성
on:
  push:
    branches:
      - main

env:
  AWS_REGION : <"ap-northeast-2">
  AWS_ROLE_ARN : <arn:aws:iam::084982019659:oidc-provider/token.actions.githubusercontent.com>

permissions:
  id-token: write
  contents: read

# 워크플로우 내의 작업
jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-22.04
    steps:
      - name: Git clone the repo
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity
