name: Node.js CI / CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - run: cd server
    - name: Use Node.js ${{ matrix.node-version }}
  
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: touch .env
    - run: echo "${{ secrets.NODE_ENV }}" > .env
      
